### ISSUE TITLE
Installation instructions seem to be outdated

### ISSUE THREAD

**Issue by luiscruz** [walkmod/walkmod-setter-getter-plugin#5]
The XML specification in the README does not look compatible with the latest version of walkmod.
Is node `<plugin>` currently being used by walkmod?
Can you please check it?

With the provided instructions I get the following output:

```
ERROR [main] - TRANSFORMATION CHAIN (default) FAILS
Sorry, it is impossible to load the bean setter-getter. Please, assure that it is a valid class name and the library which contains it is in the classpath - org.walkmod.util.location.LocationImpl@6283d8b8
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.walkmod.conf.entities.impl.ConfigurationImpl.getBean(ConfigurationImpl.java:160)
        at org.walkmod.impl.DefaultChainWalkerAdapter.prepare(DefaultChainWalkerAdapter.java:106)
        at org.walkmod.impl.DefaultChainAdapter.prepare(DefaultChainAdapter.java:159)
        at org.walkmod.impl.DefaultChainAdapterFactory.createChainProxy(DefaultChainAdapterFactory.java:49)
        at org.walkmod.WalkModFacade.executeAllChains(WalkModFacade.java:909)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:376)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:171)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:196)
Caused by: java.lang.ClassNotFoundException: setter-getter
        ... 12 more
```

**Comment by rpau** [comment]
Plugin is no longer needed in the configuration file. The README has been updated.
Thanks for your feedback.
